backend signature verification + remove duplicates + adjust threshold
hashgraph/stablecoin-studio pull request #1078
Opened 2024-03-22 10:37 UTC by AlbertoMolinaIoBuilders

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 📝

backend signature verification + remove duplicates + adjust threshold

Fixes # (issue) 🛠️

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue) 🐞
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 💥
- [ ] This change requires a documentation update 📖

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. 🧪

- [ ] Local Tests (npm run test)
- [ ] Local Example (npx tsx examples/index.ts)
- [ ] Local Github Actions (act pull_request)

**Test Configuration**:

- Node version (latest LTS):
  - [ ] 16
  - [ ] 18
  - [ ] 20

### Test Results (if any)

## Checklist:

- **Style Guidelines** (My code follows the style guidelines of this project) ✅
- **Self-Review** (I have performed a self-review of my own code) 👀
- **Code Comments** (I have commented my code, particularly in hard-to-understand areas) 💬
- **Documentation Updates** (I have made corresponding changes to the documentation) 📚
- **Warning-Free Changes** (My changes generate no new warnings) ⚠️
- **Effective Tests** (I have added tests that prove my fix is effective or that my feature works) ✔️
- **Local Test Pass** (New and existing unit tests pass locally with my changes) ✅
- **Dependency Updates** (Any dependent changes have been merged and published in downstream modules) 🔄
- **Spellcheck** (I have checked my code and corrected any misspellings) 📝

2024-03-22 11:03 UTC, MiguelLZPF approved these changes

2024-03-25 10:46 UTC, MiguelLZPF requested changes

2024-03-25 10:46 UTC, MiguelLZPF commented on package.json
Either remove ethers or use only ethers for keccak256

2024-03-25 11:03 UTC, M-Francia approved these changes

2024-03-25 13:01 UTC, MiguelLZPF approved these changes

2024-03-25 13:01 UTC, merged