chore: [BBND-469] npm workspaces
hashgraph/stablecoin-studio pull request #1235
Opened 2024-12-11 07:49 UTC by ManuIOB

**Description**:

Add NPM workspaces configuration

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-13 07:08 UTC, mishomihov00 requested changes
All workflows seems to be failing on the `npm ci` command due to a missing `package-lock.json` file. Please check.

2024-12-16 08:18 UTC, MiguelLZPF commented on package.json
> +    "husky": "^9.0.11",
"shared dependencies declared in the root package.json are installed once at the root and used by all packages that require them, avoiding duplication in sub-packages"

2024-12-16 09:03 UTC, ManuIOB commented on package.json
added, thanks

2024-12-16 09:18 UTC, ManuIOB commented on package.json
> +    "install:all": "npm install && npm run build:cli:full && npm run prepare",
updated package.json scripts

2024-12-16 09:18 UTC, ManuIOB commented on package.json
>      "install:contracts": "cd contracts && npm install",
updated package.json scripts

2024-12-16 09:29 UTC, MiguelLZPF commented on package.json
> +    "husky": "^9.0.11",
This one can also be addressed in future PRs if it is a lot of work right now... 👍🏻

2024-12-16 09:29 UTC, ManuIOB commented on package.json
> +    "husky": "^9.0.11",
true, i had issues about that, but I found a solution `"prepare": "husky install --workspace=contracts"`

2024-12-16 09:59 UTC, MiguelLZPF approved these changes

2024-12-16 14:46 UTC, merged